---
# http://about.travis-ci.org/docs/user/getting-started/
language: ruby

rvm:
  - 2.0.0
  - 1.9.3

# http://about.travis-ci.org/docs/user/database-setup/#Using-ENV-variables-and-before_script-steps
env:
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.7.5

script:
  - 'rake spec'

# @see http://about.travis-ci.org/docs/user/build-configuration/#The-Build-Matrix
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.4.0

# http://about.travis-ci.org/docs/user/notifications/#Email-notifications
notifications:
  email:
    - chocolatey-build-status@googlegroups.com
